import {
  Zap, Keyboard, Coins, Brush, TrafficCone, Calculator, Brain, ALargeSmall,
  Eye, Palette, HelpCircle, Hash, Flag, TrendingUp, Target, Grid3x3,
  Paintbrush, CircleDot, ArrowUpDown, Hammer, Clapperboard, Dices,
  LayoutGrid, CheckCircle2, Landmark, Music, Boxes, Worm, Circle,
  Copy, Binary, Link2, Map, PieChart as PieIcon, SearchCode,
  BrainCircuit, Type, Users, Waypoints, Siren, ScanSearch, Equal,
  ArrowBigUp, WholeWord, Scale,
  type LucideIcon,
} from "lucide-react";
import type { GameType } from "./games";

export const GAME_ICONS: Record<GameType, LucideIcon> = {
  tapblitz: Zap,
  typerush: Keyboard,
  priceguess: Coins,
  drawblitz: Brush,
  reaction: TrafficCone,
  mathblitz: Calculator,
  emojimemory: Brain,
  wordscramble: ALargeSmall,
  oddoneout: Eye,
  stroop: Palette,
  trivia: HelpCircle,
  countemoji: Hash,
  flagguess: Flag,
  higherlower: TrendingUp,
  aimtrainer: Target,
  simon: Grid3x3,
  colormatch: Paintbrush,
  popbubbles: CircleDot,
  speedsort: ArrowUpDown,
  whackmole: Hammer,
  emojiriddle: Clapperboard,
  ninetarget: Dices,
  patterncopy: LayoutGrid,
  truefalse: CheckCircle2,
  rhythmtap: Music,
  stacktower: Boxes,
  snake: Worm,
  perfectcircle: Circle,
  cardmatch: Copy,
  guessnumber: Binary,
  sequencenext: Link2,
  capitals: Map,
  piechart: PieIcon,
  typohunt: SearchCode,
  memorydigits: BrainCircuit,
  anagramsprint: Type,
  findpair: Users,
  connectdots: Waypoints,
  gonogo: Siren,
  spotdiff: ScanSearch,
  mathtruth: Equal,
  quickbiggest: ArrowBigUp,
  letterpop: WholeWord,
  coinsplit: Scale,
  monopoly: Landmark,
};

// One-line "how to play" per game type (shown in RoundHeader).
export const GAME_RULES: Record<GameType, string> = {
  tapblitz: "Tap sul bottone il più veloce possibile per 10 secondi.",
  typerush: "Digita la frase esatta; velocità e accuratezza contano.",
  priceguess: "Indovina il prezzo del prodotto in euro; più vicino = più punti.",
  drawblitz: "Disegna il tema in 30 secondi, poi il gruppo vota il migliore.",
  reaction: "Aspetta il segnale VERDE, poi tocca il prima possibile.",
  mathblitz: "Risolvi più operazioni possibili; gli errori tolgono punti.",
  emojimemory: "Memorizza la sequenza di emoji, poi ricomponila nell'ordine giusto.",
  wordscramble: "Ricostruisci la parola dagli anagrammi. Suggerimento sotto.",
  oddoneout: "Trova l'unica emoji diversa nella griglia; errori penalizzati.",
  stroop: "La parola scritta corrisponde al colore in cui è scritta? SÌ / NO.",
  trivia: "Rispondi alla domanda a scelta multipla; più veloce = più punti.",
  countemoji: "Conta quante emoji-target ci sono nella griglia.",
  flagguess: "Scrivi il nome del paese della bandiera. Accenti/alias accettati.",
  higherlower: "Quale città ha più abitanti? Continua finché sbagli.",
  aimtrainer: "Colpisci il bersaglio che appare. Clic fuori = miss.",
  simon: "Osserva la sequenza di colori e riproducila; sbagli = round finito.",
  colormatch: "Scegli il codice HEX che corrisponde al colore mostrato.",
  popbubbles: "Scoppia le bolle 🫧, evita le bombe 💣.",
  speedsort: "Scambia i numeri per metterli in ordine crescente il più veloce.",
  whackmole: "Colpisci le 🐹 quando spuntano, evita le 💣.",
  emojiriddle: "Indovina il film / titolo dagli emoji. C'è un suggerimento.",
  ninetarget: "Seleziona i numeri la cui somma è uguale al target.",
  patterncopy: "Memorizza lo schema acceso, poi ricopialo esattamente.",
  truefalse: "L'affermazione è vera o falsa? Errori penalizzati.",
  rhythmtap: "Tap ogni volta che il cursore entra nella zona bersaglio.",
  stacktower: "Tocca per fermare il blocco: allinealo al precedente per costruire in alto.",
  snake: "Muovi lo snake con le frecce, mangia le mele, evita di morderti.",
  perfectcircle: "Disegna un cerchio con il dito/mouse: più è perfetto, più punti.",
  cardmatch: "Gira due carte alla volta e trova le coppie. Meno errori = più punti.",
  guessnumber: "Indovina il numero da 1 a 100 con feedback più alto/più basso.",
  sequencenext: "Trova il numero che completa la sequenza tra le opzioni.",
  capitals: "Scegli la capitale corretta del paese tra le 4 opzioni.",
  piechart: "Stima con lo slider la percentuale della fetta colorata (0-100%).",
  typohunt: "Nella frase c'è una parola scritta male: cliccala.",
  memorydigits: "Memorizza i 6 numeri mostrati e poi digitali nello stesso ordine.",
  anagramsprint: "Risolvi più anagrammi possibile in tempo; ogni sbaglio penalizza.",
  findpair: "Nella griglia c'è UNA sola coppia di emoji uguali: clicca entrambe.",
  connectdots: "Tocca i pallini in ordine da 1 fino all'ultimo, il più veloce.",
  gonogo: "Tap solo quando appare il segnale VERDE; il rosso NON va toccato.",
  spotdiff: "Tra le due griglie una casella è diversa: cliccala nella griglia di destra.",
  mathtruth: "L'operazione mostrata è giusta o sbagliata? Tap SÌ o NO.",
  quickbiggest: "Tra i 4 numeri, tocca il più grande il più in fretta possibile.",
  letterpop: "Tocca SOLO le vocali che appaiono; consonanti e mancate penalizzano.",
  coinsplit: "Assegna ogni moneta a sinistra o destra così che le due pile abbiano la stessa somma.",
  monopoly: "Tira i dadi, compra proprietà, incassa affitti. Vince chi accumula più patrimonio.",
};
